# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'PYTHON'), ('dj', 'DJANGO'), ('ra', 'RESTAPI'), ('ui', 'UI')], max_length=100)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'Hyderabad'), ('bang', 'Bangalore'), ('che', 'Chennai'), ('pun', 'Pune')], max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
            ],
        ),
    ]
